# Generated by Django 4.1.1 on 2022-11-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AF', 'A fazer'), ('FE', 'FEITA')], max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
