# Generated by Django 4.1 on 2022-10-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
